# Generated by Django 2.1.5 on 2019-01-24 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='issue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='chat.Issue'),
        ),
    ]
