# Generated by Django 2.1.5 on 2019-03-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190124_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('Hign', 'High'), ('Normal', 'Normal'), ('Low', 'Low')], max_length=1),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('InProgress', 'InProgress'), ('Closed', 'Closed')], max_length=1),
        ),
    ]
