# Generated by Django 2.1.5 on 2019-04-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190326_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(default='test', max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='space',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='due_date'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(blank=True, choices=[('Hign', 'High'), ('Normal', 'Normal'), ('Low', 'Low')], max_length=1, null=True),
        ),
    ]
