# Generated by Django 2.1.5 on 2019-04-07 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20190407_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.Issue'),
        ),
    ]
